name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: 'Build Node with pmm master'
      run: |
        yarn pack
        git clone -b mael/pmm --depth=1 https://github.com/arcanis/node.git node && cd node
        git config user.name 'John Doe'
        git config user.email 'john@example.org'
        rm -rf deps/pmm && tar xvf ../package.tgz && mv package deps/pmm
        git add . && git commit -m 'Updates pmm'
        ./configure
        DISTTYPE=nightly DATESTRING=YYYY-MM-DD COMMIT=XXXX make binary -j8

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: node/node-v15.0.0-nightlyYYYY-MM-DDXXXX-*.tgz
