name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
        - 14
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    name: '${{matrix.platform}} w/ Node.js ${{matrix.node}}.x'
    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v2

    - name: 'Use Node.js ${{matrix.node}}.x'
      uses: actions/setup-node@master
      with:
        node-version: ${{matrix.node}}.x

    - run: yarn install --immutable
    - run: yarn build # We need the stubs to run the tests
    - run: yarn eslint
    - run: NOCK_ENV=replay yarn jest
      shell: bash
